services:
  rds.hackathon.acmucsd.local:
    container_name: rds.hackathon.acmucsd.local
    image: postgres:17
    restart: always
    ports:
      - '${RDS_PORT}:5432'
    environment:
      POSTGRES_DB: ${RDS_DATABASE}
      POSTGRES_USER: ${RDS_USER}
      POSTGRES_PASSWORD: ${RDS_PASSWORD}
