name: Backend - Linting and Testing
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./server
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        working-directory: ./server
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./server
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ./server
        run: yarn test
